language: scala
script: ./tools/travis-script.sh
branches:
  only:
    - master
    - scalacheck2
    - 1.12.x
scala:
  - 2.10.5
  - 2.11.7
  - 2.12.0-M2
jdk:
  - oraclejdk8
env:
  matrix:
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=4 DEPLOY=false
    - PLATFORM=jvm SBT_PARALLEL=false WORKERS=4 DEPLOY=false
    - PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
sudo: false
